### PR TITLE
#Add  Code_Of_Conduct File

### LINKED ISSUE #1: Add Code of Conduct
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext labels.

### PR DESCRIPTION
**Pull request by ghost**
Closes #1 

This PR has been raised to address the addition of code of conduct markdown file to the users of Frontend Mentor Projects. A standard template has been used and modified to cater to the project and an email Id of the author has been added for reporting purposes.

Thank you. Please add level1 and gssoc24-ext labels to this PR. Thanks again.

### CODE REVIEW

**Comment by KiranBaliga** [comment]
@beRajeevKumar Please let me know if i have to modify something.

**Review by rajeevkumar504 — APPROVED** [review]
Nice work, @KiranBaliga! Thank you for your contribution.

**Comment by KiranBaliga** [comment]
@beRajeevKumar Thank you, please add level1 label as it wont be counted later. sorry for the trouble.

**Comment by KiranBaliga** [comment]
@beRajeevKumar I kindly request you to add level1 label so that it counts to the leader board. Thank you!

**Pull request merged**
